### ISSUE TITLE
堆的概念是错的吧？

### ISSUE THREAD

**Issue by ladieman217** [ecmadao/algorithms#1]
In computer science, a heap is a specialized tree-based data structure that satisfies the heap property: if P is a parent node of C, then the key (the value) of P is either greater than or equal to (in a max heap) or less than or equal to (in a min heap) the key of C.[1] The node at the "top" of the heap (with no parents) is called the root node.[heap](https://en.wikipedia.org/wiki/Heap_(data_structure))

**Comment by ecmadao** [comment]
感谢指正。很久以前写的东西了，一直没有回头去检查。
队列：先进先出
栈：先进后出
堆栈：实际上就是栈，只是一种通俗说法

**Comment by ecmadao** [comment]
@YUFENGWANG 
已更新，再次感谢！
